{
 "title": "Mikrotik MKTXP Monitor",
 "description": "Mikrotik MKTXP Exporter metrics",
 "tags": [
  "mikrotik",
  "dashboard",
  "mktxp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(mktxp_system_identity_info, routerboard_address)"
    }
   },
   {
    "name": "interface_name",
    "query": {
     "query": "mktxp_interface_rx_byte_total{routerboard_address=\"$node\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Identity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_identity_info{routerboard_address=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Public IP",
   "type": "stat",
   "description": "Public IP address of the networking device.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_public_ip_address_info{routerboard_address=\"$node\"}",
     "legendFormat": "{{public_address}}"
    }
   ]
  },
  {
   "title": "Routerboard HW",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_uptime{routerboard_address=\"$node\"}",
     "legendFormat": "{{board_name}}"
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_uptime{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_uptime{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "legendFormat": "{{version}} ",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Newest Version",
   "type": "stat",
   "description": "The newest available version",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_update_available{routerboard_address=\"$node\"}",
     "legendFormat": "{{newest_version}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_routerboard_voltage{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_active_users_info{routerboard_address=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mktxp_system_routerboard_temperature{routerboard_address=\"$node\"} or mktxp_system_cpu_temperature{routerboard_address=\"$node\"}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "(1 - mktxp_system_free_memory{routerboard_address=\"$node\"} / mktxp_system_total_memory{routerboard_address=\"$node\"})*100",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used RAM Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mktxp_system_cpu_load{routerboard_address=\"$node\"}",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - mktxp_system_free_hdd_space{routerboard_address=\"$node\"} / mktxp_system_total_hdd_space{routerboard_address=\"$node\"})*100",
     "legendFormat": "HDD Utilization"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mktxp_system_cpu_load{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "legendFormat": "{{cpu}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "HDD Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_total_hdd_space{routerboard_address=\"$node\"} - mktxp_system_free_hdd_space{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_total_hdd_space{routerboard_address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Total memory" },
     "legendFormat": "Total memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Interface traffic ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": " rate(mktxp_interface_rx_byte_total{routerboard_address=\"$node\"}[$__rate_interval]) * 8 != 0",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In | {{ name }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "- rate(mktxp_interface_tx_byte_total{routerboard_address=\"$node\"}[$__rate_interval]) * 8 != 0",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out | {{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Incoming Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(mktxp_interface_rx_packet_total{routerboard_address=\"$node\"}[$__rate_interval]) != 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Outgoing packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(mktxp_interface_tx_packet_total{routerboard_address=\"$node\"}[$__rate_interval]) != 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Latency (RTT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(probe_icmp_duration_seconds{phase=\"rtt\"}[$__rate_interval])) by (instance)\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Latency (DNS resolution)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(probe_icmp_duration_seconds{phase=\"resolve\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg_over_time(probe_success[$__rate_interval]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DHCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "DHCP Leases by Server",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 139 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_dhcp_lease_active_count{routerboard_address=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ server }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "DHCP Leases",
     "type": "table",
     "gridPos": { "h": 11, "w": 19, "x": 5, "y": 139 },
     "targets": [
      {
       "expr": "mktxp_dhcp_lease_info{routerboard_address=\"$node\"}"
      }
     ]
    },
    {
     "title": "Total DHCP Leases",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 147 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "sum(mktxp_dhcp_lease_active_count{routerboard_address=\"$node\"})",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "In - {{ server }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Routes",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 140 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mktxp_routes_total_routes{routerboard_address=\"$node\"}"
      }
     ]
    },
    {
     "title": "Routes per protocol",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 4, "x": 2, "y": 140 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_routes_protocol_count{routerboard_address=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/errors on interface/" },
       "legendFormat": "{{protocol}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Ethernet Ports: Full Duplex",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 140 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mktxp_interface_full_duplex{routerboard_address=\"$node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Interface Errors",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 140 },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_interface_rx_error_total{routerboard_address=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/errors on interface/" },
       "legendFormat": "In Errors | {{name}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "mktxp_interface_tx_error_total{routerboard_address=\"$node\"}",
       "legendFormat": "Out Errors | {{name}}"
      }
     ]
    },
    {
     "title": "Ethernet Ports: Status",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 145 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "mktxp_interface_status{routerboard_address=\"$node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Rates",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "expr": "mktxp_interface_rate{routerboard_address=\"$node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "POE",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 152 },
     "targets": [
      {
       "expr": "mktxp_poe_info{routerboard_address=\"$node\"}"
      }
     ]
    }
   ]
  },
  { "title": "Firewall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Logged Firewall Rules Traffic ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_filter_total{routerboard_address=\"$node\", log=\"0\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Logged Raw Firewall Rules Traffic ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_raw_total{routerboard_address=\"$node\", log=\"0\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Firewall Rules Traffic (IPv6)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(mktxp_firewall_filter_ipv6_total{routerboard_address=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Firewall Rules Traffic (IPv4)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_filter_total{routerboard_address=\"$node\"}[$__rate_interval])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Raw Firewall Rules Traffic (IPv4)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_raw_total{routerboard_address=\"$node\"}[$__rate_interval])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Internet Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    { "expr": "mktxp_internet_bandwidth", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Internet Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "mktxp_internet_latency", "legendFormat": "latency" }
   ]
  },
  {
   "title": "Global Active Users",
   "type": "table",
   "description": "Shows active users on all monitored devices.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "targets": [
    { "expr": "mktxp_active_users_info", "legendFormat": "__auto" }
   ]
  },
  { "title": "Netwatch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Status over time",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "max_over_time(mktxp_netwatch_status{routerboard_address=\"$node\"}[1m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Netwatch Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "mktxp_netwatch_info{routerboard_address=\"$node\"}"
    }
   ]
  },
  {
   "title": "Wireless",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "panels": [
    {
     "title": "Noise Floor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
     "targets": [
      {
       "expr": "mktxp_wlan_noise_floor{routerboard_address=\"$node\"}",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "Overall Tx CCQ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
     "targets": [
      {
       "expr": "mktxp_wlan_overall_tx_ccq{routerboard_address=\"$node\"}",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "Client Devices",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
     "targets": [
      {
       "expr": "mktxp_wlan_clients_devices_info{routerboard_address=\"$node\"}"
      }
     ]
    },
    {
     "title": "Number of clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
     "targets": [
      {
       "expr": "mktxp_wlan_registered_clients{routerboard_address=\"$node\"}",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "WLAN Clients Tx CCQ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
     "targets": [
      {
       "expr": "mktxp_wlan_clients_tx_ccq{routerboard_address=\"$node\"}",
       "legendFormat": "{{dhcp_name}}"
      }
     ]
    },
    {
     "title": "Clients Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_wlan_clients_tx_bytes_total{routerboard_address=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "In - {{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_wlan_clients_rx_bytes_total{routerboard_address=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Outgoing traffic on interface ether1-gateway"
       },
       "legendFormat": "Out - {{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Clients Signal Strength",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_wlan_clients_signal_strength{routerboard_address=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Clients  Signal-to-Noise ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_wlan_clients_signal_to_noise{routerboard_address=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "CAPsMAN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Remote Caps",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mktxp_capsman_remote_caps_info{routerboard_address=\"$node\"}",
       "legendFormat": "{{identity}}"
      }
     ]
    },
    {
     "title": "CAPsMAN Clients",
     "type": "table",
     "gridPos": { "h": 15, "w": 18, "x": 6, "y": 144 },
     "targets": [
      {
       "expr": "mktxp_capsman_clients_devices_info{routerboard_address=\"$node\"}"
      }
     ]
    },
    {
     "title": "CAPsMAN Registrations",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 151 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_capsman_registrations_count{routerboard_address=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ interface }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "sum(mktxp_capsman_registrations_count{routerboard_address=\"$node\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "CAPsMAN Frequencies",
     "type": "table",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 159 },
     "targets": [
      {
       "expr": "mktxp_capsman_interfaces_info{routerboard_address=\"$node\"}"
      }
     ]
    },
    {
     "title": "Registered Client Signal Strength",
     "type": "bargauge",
     "gridPos": { "h": 16, "w": 6, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_capsman_clients_signal_strength{routerboard_address=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "CAPsMan Clients Signal Strength",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_capsman_clients_signal_strength{routerboard_address=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "CAPsMAN Clients Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 176 },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_capsman_clients_tx_bytes_total{routerboard_address=\"$node\"}[$__rate_interval]) * 8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "In | {{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_capsman_clients_rx_bytes_total{routerboard_address=\"$node\"}[$__rate_interval]) * 8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Outgoing traffic on interface ether1-gateway"
       },
       "legendFormat": "Out | {{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface_name",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 257 },
     "repeat": "interface_name",
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "(rate(mktxp_interface_rx_byte_total{routerboard_address=\"$node\", name=\"$interface_name\"}[$__rate_interval]) * 8)",
       "legendFormat": "rx"
      },
      {
       "expr": "(rate(mktxp_interface_tx_byte_total{routerboard_address=\"$node\", name=\"$interface_name\"}[$__rate_interval]) * 8)",
       "legendFormat": "tx"
      }
     ]
    }
   ]
  },
  {
   "title": "MKTXP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "Python Version",
     "type": "stat",
     "description": "The version of Python running the Prometheus exporter.",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 146 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "python_info", "legendFormat": "{{implementation}} {{version}}" }
     ]
    },
    {
     "title": "MKTXP Collection Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 146 },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_collection_time_total{routerboard_address=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "sum(rate(mktxp_collection_time_total{routerboard_address=\"$node\"}[4m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "MKTXP Collection Times",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 6, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_collection_time_total{routerboard_address=\"$node\"}[4m])  ",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Memory Footprint",
     "type": "timeseries",
     "description": "Memory metrics about the Mikrotik Metric Exporter for Prometheus.",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "process_resident_memory_bytes", "legendFormat": "{{__name__}}" },
      { "expr": "process_virtual_memory_bytes", "legendFormat": "{{__name__}}" }
     ]
    },
    {
     "title": "CPU Usage (%)",
     "type": "timeseries",
     "description": "The CPU usage caused by the Prometheus exporter process. This is NOT the overall CPU usage.",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total[30s]) * 100",
       "legendFormat": "cpu_usage"
      }
     ]
    }
   ]
  }
 ]
}