# my global config
global:
  scrape_interval:     120s # By default, scrape targets every 15 seconds.
  evaluation_interval: 120s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      origin_prometheus: mikrotik-mktxp
  #    monitor: 'mikrotik-monitoring'
      

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'mikrotik'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["mikrotik-mktxp:49090"]
#            - 'mikrotik_exporter:9436'
#            - 'mktxp:49090'
            
  - job_name: 'node'
    static_configs:
      - targets: ['mikrotik-node:9100']
      
  - job_name: nextdns
    scrape_interval: 1m
    static_configs:
      - targets: ['mikotik-nextdns:9948']
  
  - job_name: 'blackbox'
    scrape_interval: 1s
    metrics_path: /probe
    params:
      module: [icmp_ttl5]  # use ICMP as the ping protocol
    static_configs:
      - targets:
        - 1.1.1.1
        - 8.8.8.8
        - 9.9.9.9
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackbox-dns-monitor'
    scrape_interval: 5s
    metrics_path: /probe
 #   params:
 #     module: [google_dns]  # use DNS as the ping protocol
    relabel_configs:
    # Populate domain label with domain portion of __address__
    - source_labels: [__address__]
      regex: (.*):.*$
      replacement: $1
      target_label: domain
    # Populate instance label with dns server IP portion of __address__
    - source_labels: [__address__]
      regex: .*:(.*)$
      replacement: $1
      target_label: instance
    # Populate module URL parameter with domain portion of __address__
    # This is a parameter passed to the blackbox exporter
    - source_labels: [domain]
      target_label: __param_module
    # Populate target URL parameter with dns server IP
    - source_labels: [instance]
      target_label: __param_target
    # Populate __address__ with the address of the blackbox exporter to hit
    - target_label: __address__
      replacement: blackbox:9115
    static_configs:
      - targets:
        - www.google.com:8.8.8.8
        - www.google.com:1.1.1.1
        - www.google.com:9.9.9.9
        - www.google.com:208.67.222.222

